name: feature-branch-checks
run-name: ${{ github.actor }} is running checks on feature branch
on:
  push

jobs:
  feature-branch-checks:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup
        id: setup
        run: npm ci

      - name: Unit tests
        run: npm run test:unit:coverage

      - name: Build
        id: build
        run: ./scripts/build.sh
        env:
          ENV: DEV

      - name: Deploy
        id: deploy
        run: ./scripts/deploy.sh
        env:
          ENV: DEV